Test on Python 3.13 and Django 5.2

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -2,69 +2,68 @@ name: Test
 
 on:
   push:
-    branches: [ master ]
+    branches: [master]
   pull_request:
-    branches: [ master ]
+    branches: [master]
 
 permissions:
   contents: read # to fetch code (actions/checkout)
 
 jobs:
-
   build:
     runs-on: ubuntu-latest
     name: Python${{ matrix.python-version }}/Django${{ matrix.django-version }}
     strategy:
       matrix:
-        python-version: ["3.10", "3.11", "3.12"]
-        django-version: ["3.2.23", "4.0.8", "4.1.3", "4.2", "5.0", "5.1"]
+        python-version: ["3.10", "3.11", "3.12", "3.13"]
+        django-version: ["3.2.23", "4.0.8", "4.1.3", "4.2", "5.0", "5.1", "5.2"]
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v4.2.0
-      with:
-        python-version: ${{ matrix.python-version }}
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4.2.0
+        with:
+          python-version: ${{ matrix.python-version }}
 
-    - name: Start Redis
-      uses: supercharge/redis-github-action@1.4.0
+      - name: Start Redis
+        uses: supercharge/redis-github-action@1.4.0
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install django==${{ matrix.django-version }} \
-          redis django-redis pyyaml rq sentry-sdk
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install django==${{ matrix.django-version }} \
+            redis django-redis pyyaml rq sentry-sdk
 
-    - name: Run Test
-      run: |
-        `which django-admin` test django_rq --settings=django_rq.tests.settings --pythonpath=.
+      - name: Run Test
+        run: |
+          `which django-admin` test django_rq --settings=django_rq.tests.settings --pythonpath=.
 
   mypy:
     runs-on: ubuntu-latest
     name: Type check
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Set up Python 3.8
-      uses: actions/setup-python@v4.2.0
-      with:
-        python-version: "3.8"
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v4.2.0
+        with:
+          python-version: "3.8"
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install django-stubs[compatible-mypy] rq types-redis
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install django-stubs[compatible-mypy] rq types-redis
 
-    - name: Run mypy
-      continue-on-error: true
-      id: mypy
-      run: |
-        mypy django_rq
-    
-    - name: Set Status
-      if: steps.mypy.outcome == 'failure'
-      run: |
-        echo "Mypy found errors, marking check as neutral"
-        exit 78  # Exit code 78 results in a neutral check
+      - name: Run mypy
+        continue-on-error: true
+        id: mypy
+        run: |
+          mypy django_rq
+
+      - name: Set Status
+        if: steps.mypy.outcome == 'failure'
+        run: |
+          echo "Mypy found errors, marking check as neutral"
+          exit 78  # Exit code 78 results in a neutral check
